#ifndef APPWINDOWSTATENUM_HPP
#define APPWINDOWSTATENUM_HPP

enum AppWindowStat{
    APP_WINDOW_STAT_LOGIN,
    APP_WINDOW_STAT_REGISTER,
    APP_WINDOW_STAT_LOGGED_IN
};

#endif // APPWINDOWSTATENUM_HPP
