#ifndef APPWINDOWLOGGEDINSTATUS_HPP
#define APPWINDOWLOGGEDINSTATUS_HPP

enum AppWindowLoggedInStatus{
    LOGGED_IN_PANEL_YOUR_ACCOUNT_STAT,
    LOGGED_IN_PANEL_MY_BOOKS_STAT,
    LOGGED_IN_PANEL_LIBRARY_STAT,
    LOGGED_IN_PANEL_READERS_STAT,
    LOGGED_IN_PANEL_BOOKS_STAT,
    LOGGED_IN_PANEL_USERS_STAT,
    LOGGED_IN_PANEL_USER_DATA_STAT,
    LOGGED_IN_PANEL_ADD_BOOK_STAT,
    LOGGED_IN_PANEL_ADD_USER_STAT,
    LOGGED_IN_PANEL_BOOK_DATA_STAT,
    LOGGED_IN_PANEL_BOOK_LOG_STAT,
    NUMB_OF_LOGGED_IN_PANEL_STATS
};

#endif // APPWINDOWLOGGEDINSTATUS_HPP
