#ifndef DATAPANELMODE_HPP
#define DATAPANELMODE_HPP

enum DataPanelMode{
    REGISTER_MODE,
    EDITABLE_MODE,
    ADMIN_EDITABLE_MODE,
    ADMIN_REGISTER_MODE,
    DATA_MODE,
    ADMIN_DATA_MODE,
    NUMB_OF_DATA_PANEL_MODES
};

#endif // DATAPANELMODE_HPP
