#ifndef LOGGEDINCONTROLPANELREADERFUNC_HPP
#define LOGGEDINCONTROLPANELREADERFUNC_HPP

enum LoggedInControlPanelReaderFunc{
    LOGGED_IN_PANEL_READER_YOUR_ACCOUNT,
    LOGGED_IN_PANEL_READER_YOUR_BOOKS,
    LOGGED_IN_PANEL_READER_LIBRARY,
    LOGGED_IN_PANEL_READER_LOGOUT,
    NUMB_OF_LOGGED_IN_CONTROL_PANEL_READER_FUNC
};

#endif // LOGGEDINCONTROLPANELREADERFUNC_HPP
