#ifndef LOGGEDINCONTROLPANELLIBRARIANFUNC_HPP
#define LOGGEDINCONTROLPANELLIBRARIANFUNC_HPP

enum LoggedInControlPanelLibrarianFunc{
    LOGGED_IN_PANEL_LIBRARIAN_YOUR_ACCOUNT,
    LOGGED_IN_PANEL_LIBRARIAN_READERS,
    LOGGED_IN_PANEL_LIBRARIAN_BOOKS,
    LOGGED_IN_PANEL_LIBRARIAN_ADD_BOOK,
    LOGGED_IN_PANEL_LIBRARIAN_ADD_USER,
    LOGGED_IN_PANEL_LIBRARIAN_LOG_LIST,
    LOGGED_IN_PANEL_LIBRARIAN_LOGOUT,
    NUMB_OF_LOGGED_IN_PANEL_LIBRARIAN_FUNC
};

#endif // LOGGEDINCONTROLPANELLIBRARIANFUNC_HPP
