#ifndef LOGGEDINPANELADMINFUNC_HPP
#define LOGGEDINPANELADMINFUNC_HPP

enum LoggedInPanelAdminFunc{
    LOGGED_IN_PANEL_ADMIN_YOUR_ACCOUNT,
    LOGGED_IN_PANEL_ADMIN_USERS,
    LOGGED_IN_PANEL_ADMIN_BOOKS,
    LOGGED_IN_PANEL_ADMIN_ADD_BOOK,
    LOGGED_IN_PANEL_ADMIN_ADD_USER,
    LOGGED_IN_PANEL_ADMIN_LOG_LIST,
    LOGGED_IN_PANEL_ADMIN_LOGOUT,
    NUMB_OF_LOGGED_IN_PANEL_ADMIN_FUNC
};
#endif // LOGGEDINPANELADMINFUNC_HPP
