#ifndef PROMPTPANELSTATUSENUM_HPP
#define PROMPTPANELSTATUSENUM_HPP

enum PromptPanelStatus{
  PROMPT_PANEL_HIDDEN,
  PROMPT_PANEL_MINIMIZED,
  PROMPT_PANEL_MAXIMIZED
};

#endif // PROMPTPANELSTATUSENUM_HPP
