#ifndef PROMPTTYPEENUM_HPP
#define PROMPTTYPEENUM_HPP

enum PromptType{
    PROMPT_TYPE_DISPLAY_DATA_AVAILABLE,
    PROMPT_TYPE_DATA_NOT_SAVED,
    PROMPT_TYPE_LONG_STRINGS,
    PROMPT_TYPE_DATA_NOT_READED,
    PROMPT_TYPE_DEFAULT
};

#endif // PROMPTTYPEENUM_HPP
